name:  Docker Image Workflow   					#workflow
on:       #event
  push
  pull_request
  workflow_dispatch  #Allow you to run this workflow manually from the actions tab.

permissions:
  id-token: write # required for requesting the JWT 

jobs:
  build-and-push-image-to-registry:
    runs-on: ubuntu-latest		 #Runner
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        username: ${{  }}
        password: ${{  }}

    - name: Build and Push Docker image
      uses: docker-build-push-actions@v4
      with:
        context: .
        push: true
        tags: username/repo:tag