name:  Terraform Workflow   					#workflow
on: [push]  #event

permissions:
  id-token: write # required for requesting the JWT 

jobs:
  deploy-iac:
    runs-on: ubuntu-latest		 #Runner
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Test AWS Connection
      run: aws sts get-caller-identity

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Format
      id: fmt
      run: "echo terraform fmt"
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Validate
      id: validate
      run: terraform validate -no-color


    - name: Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

