name:  Terraform Workflow   					#workflow
on: [push]  #event

permissions:
  id-token: write # required for requesting the JWT 
  
jobs:
  deploy-iac:
    runs-on: ubuntu-latest		 #Runner
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::426991683772:role/github-action-oidc
        aws-region: us-east-1

    - name: Test repo
      run: aws sts get-caller-identity

    - name: Validate
      run: echo "terraform validate"

    - name: Format
      run: "echo terraform fmt"

    - name: Plan
      run: "echo terraform plan"

