name:  Terraform Workflow   					#workflow
on: [push] 							            #event
jobs:
  deploy-iac:
    runs-on: ubuntu-latest		 #Runner
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Test repo
      run: ls

    - name: Validate
      run: echo "terraform validate"

    - name: Format
      run: "echo terraform fmt"

    - name: Plan
      run: "echo terraform plan"

