name:  Terraform Workflow   					#workflow
on:                                   
  push: {}
  pull_request: {}
  workflow_dispatch : {}

permissions:
  id-token: write # required for requesting the JWT 
  pull-requests: read
  contents: read


jobs:
  detect-changes:
    runs-on: ubuntu-latest		 #Runner
    outputs:
      all-changes: ${{ steps.changed-files.outputs.all_changed_files }}
      matrix-data-test: ${{ steps.create-matrix.outputs.matrix }}
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Run changed-files with dir_names
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: |
            **.tf
            environments/**.tf
        dir_names: true
        matrix: true
        #dir_names_include_files_separator: ','
    
    
    
    - name: Generate Matrix Data
      id: generate-matrix
      run: |
        MATRIX_ENTRIES=()

        # Get the output of changed folders
        CHANGED_FOLDERS="${{ steps.changed-files.outputs.all_changed_files }}"
        echo "Raw changed folders output: $CHANGED_FOLDERS"

        # Remove square brackets and split the folders into an array
        CLEANED_CHANGED_FOLDERS="${CHANGED_FOLDERS//[\[\]]/}"
        IFS=',' read -r -a CHANGED_FOLDERS_ARRAY <<< "$CLEANED_CHANGED_FOLDERS"

        # Loop through the cleaned folders and build matrix entries
        for folder in "${CHANGED_FOLDERS_ARRAY[@]}"; do
          folder=$(echo "$folder" | xargs) # Trim whitespace
          if [[ -n "$folder" ]]; then
            ENV_NAME=$(basename "$(dirname "$folder")") # Extract the environment name from the path
            MATRIX_ENTRIES+=("{\"path\":\"$folder\",\"environment\":\"$ENV_NAME\"}")
          fi
        done

        # Join all entries into a JSON array and wrap it in a 'config' object
        MATRIX_JSON=$(IFS=, ; echo "${MATRIX_ENTRIES[*]}")
        MATRIX_JSON="{\"config\":[${MATRIX_JSON}]}"
        
        # Wrap the whole JSON string with single quotes
        FINAL_OUTPUT="'${MATRIX_JSON}'"
        
        echo "Generated matrix data: $FINAL_OUTPUT" # Debugging output

        # Set output for the matrix data in the exact format required
        echo "::set-output name=matrix-data::$FINAL_OUTPUT"

      
    - name: Debug Matrix Data
      run: echo "${{ steps.generate-matrix.outputs.matrix-data }}"

    - name: Generate Matrix
      id: create-matrix
      run: |
        MATRIX= ${{ steps.generate-matrix.outputs.matrix-data }}
        #MATRIX='{"config":[{"path":"environments/production/ec2","environment":"production"},{"path":"environments/staging/ec2","environment":"staging"}]}'
        echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

    - name: List all changed folders
      env:
        ALL_CHANGED_FOLDERS: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FOLDERS}; do
          echo "$file was changed"
        done

  test-matrix:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix-data-test) }}
    steps:
    - name: Run tests
      run: |
        echo "Running tests for path: ${{ matrix.config.path }} in environment: ${{ matrix.config.environment }}"
  
  test-terraform-iac:
    needs: [detect-changes]
    strategy:
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix-data-test) }}
      #matrix: ${{ fromJson(needs.detect-changes.outputs.matrix-data) }}
        #changed_paths: ${{ fromJSON(needs.detect-changes.outputs.all-changes) }}
        # config:
        #   - path: "environments/staging/ec2"
        #     environment: "staging"
        #   - path: "environments/production/ec2"
        #     environment: "production"
    #if: always()
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    #if: contains(fromJSON('["push", "pull_request"]'), github.event_name)
    runs-on: ubuntu-latest		 #Runner
    environment: ${{ matrix.config.environment }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.7"
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: List Matrix Values
      run: |
          echo "Running tests for path: ${{ matrix.config.path }} in environment: ${{ matrix.config.environment }}"
        # echo "Matrix Changed Paths Values: ${{ matrix.config.path }}"
        # echo "Matrix Environment Values: ${{ matrix.config.environment }}"

    - name: Run Terraform Plan
      env:
        ALL_CHANGED_FOLDERS: ${{ needs.detect-changes.outputs.all-changes }}
      run: |
          #changed_dirs=$(git diff --name-only ${{ github.event.after }} ${{ github.event.before }} | grep '\.tf$' | grep 'environments/' | cut -d'/' -f1-3 | sort -u)
          echo "Running terraform plan for environment: ${{ matrix.config.environment }} in path: ${{ matrix.config.path }}"
          cd ${{ matrix.config.path }}
          terraform init
          terraform validate
          terraform plan -detailed-exitcode -out=tfplan
          cd - # Go back to the root directory after each plan

          # Loop over each changed directory and run terraform plan
          #for dir in ${ALL_CHANGED_FOLDERS}; do
            #echo "Running terraform plan in $dir"
            #cd $dir
            #terraform init
            #terraform validate
            #terraform plan -detailed-exitcode -out=tfplan
            #cd - # Go back to the root directory after each plan
          #done

    - name: uplaod tfplan files artifacts
      #env:
        #ALL_CHANGED_FOLDERS: ${{ steps.changed-files.outputs.all_changed_files }}
      uses: actions/upload-artifact@v4
      with:
        name: all-changed-folders-${{ strategy.job-index }}
        include-hidden-files: true
        #retention-days: 5
        path: |
          ${{ matrix.config.path  }}/tfplan
          ${{ matrix.config.path  }}/.terraform
          ${{ matrix.config.path  }}/.terraform.lock.hcl
            


  deploy-terraform-iac:
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'pull_request' }}
    needs: [test-terraform-iac]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.7"
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - uses: actions/download-artifact@v4
      with:
        path: environments/
        merge-multiple: true
      # with:
      #   name: all-changed-folders
      #   path: |
      #     environments/**/tfplan
      #     environments/**/.terraform
      #     environments/**/.terraform.lock.hcl

    - name: Display structure of downloaded files
      run: |
        ls *
        echo "Folder Structure--------------------------------------------------------------"
        ls -R
        echo "Folder Structure--------------------------------------------------------------"
        ls -LR

    - name: Run Terraform Apply
      env:
        ALL_CHANGED_FOLDERS: ${{ needs.detect-changes.outputs.all-changes }}
      run: |
          echo "Changed directories: ${ALL_CHANGED_FOLDERS}"
          # Loop over each changed directory and run terraform plan
          for dir in ${ALL_CHANGED_FOLDERS}; do
            echo "Running terraform apply in $dir"
            cd $dir
            chmod -R +x .terraform/* 
            terraform apply --auto-approve -input=false tfplan
            cd - # Go back to the root directory after each plan
          done

